version: '3.2'

volumes:
  calculation-commission-db:
    driver: local

services:
  postgres:
    image: postgres:12.8
    container_name: calculation-commission-db
    volumes:
      - type: volume
        source: calculation-commission-db
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: commission
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5437:5432"